apiVersion: v1
kind: Service
metadata:
  name: ml-score-lb
  labels:
    app: ml-score-api
  namespace: ml-app
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: ml-score-api